INSERT INTO users (name, age) VALUES ('Emma', 25);
INSERT INTO users (name, age) VALUES ('Olivia', 27);
INSERT INTO users (name, age) VALUES ('Ava', 29);
INSERT INTO users (name, age) VALUES ('Isabelle', 30);
INSERT INTO users (name, age) VALUES ('Sophia', 26);
INSERT INTO users (name, age) VALUES ('Charlotte', 23);
INSERT INTO users (name, age) VALUES ('Mia', 35);
INSERT INTO users (name, age) VALUES ('Amelia', 45);
INSERT INTO users (name, age) VALUES ('Harper', 40);
INSERT INTO users (name, age) VALUES ('Evelyn', 19);
INSERT INTO users (name, age) VALUES ('Liam', 21);
INSERT INTO users (name, age) VALUES ('Noah', 20);
INSERT INTO users (name, age) VALUES ('William', 23);
INSERT INTO users (name, age) VALUES ('James', 20);
INSERT INTO users (name, age) VALUES ('Oliver', 51);
INSERT INTO users (name, age) VALUES ('Benjamin', 18);
INSERT INTO users (name, age) VALUES ('Elijah', 24);
INSERT INTO users (name, age) VALUES ('Lucas',35);
INSERT INTO users (name, age) VALUES ('Mason', 37);
INSERT INTO users (name, age) VALUES ('Logan', 38);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Kitchen_Equipment', 'Equipment', 520000, 2020-07-06, 2020-06-07);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('painting', 'Repairs', 2500, 2020-07-07, 2020-06-08);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('dinning_chairs', 'Furniture', 7000, 2020-19-07, 2020-31-07);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('tables', 'Furniture', 1000, 2020-07-06, 2020-06-07);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Serving_Table', 'Equipment', 15000, 2020-15-06, 2020-25-07);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('flowers', 'Landscape', 2000, 2020-07-11, 2020-06-12);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('signage', 'Landscape', 10000, 2020-30-06, 2020-06-07);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Food', 'Supplies', 30000, 2020-07-06, 2020-06-07);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('software', 'Technology', 15000, 2020-07-06, 2020-06-07);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Light_Fixture', 'Repairs', 2000, 2020-07-06, 2020-06-07);
